### ISSUE TITLE
DaskTaskRunner gives unhandled exception when awaiting task result

### ISSUE THREAD

**Issue by njthompson-viv** [PrefectHQ/prefect-dask#92] opened 2023-04-25 23:52 UTC
# Expectation

I'm trying to write an asynchronous flow using a DaskTaskRunner. The crux of the flow is the ability to wait for the result of a particular task run. When I use a `ConcurrentTaskRunner`, everything works fine, and passes without any issues. When I switch to using a `DaskTaskRunner`, I keep running into an error along the lines of `TypeError: object State can't be used in 'await' expression`.

# Example

When using a `ConcurrentTaskRunner`, i.e. the following code, the flow runs fine,

```
import asyncio
import prefect
from prefect.task_runners import ConcurrentTaskRunner

@prefect.task
async def square(x: int) -> int:
    return x * x

@prefect.flow(name="test", task_runner=ConcurrentTaskRunner())
async def my_flow():
    future = await square.submit(3)
    result = await future.result()

asyncio.run(my_flow())
```

When this is changed to a `DaskTaskRunner`, the same code fails,

```
import asyncio
import prefect
from prefect_dask import DaskTaskRunner

@prefect.task
async def square(x: int) -> int:
    return x * x

@prefect.flow(name="test", task_runner=DaskTaskRunner())
async def my_flow():
    future = await square.submit(3)
    result = await future.result()

asyncio.run(my_flow())
```

This produces the following traceback,

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/user/mamba/envs/dev/lib/python3.10/site-packages/prefect/engine.py", line 669, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/user/mamba/envs/dev/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/user/mamba/envs/dev/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "<ipython-input-1-7498f128f9b2>", line 12, in my_flow
    result = await future.result()
  File "/home/user/mamba/envs/dev/lib/python3.10/site-packages/prefect/futures.py", line 241, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/home/user/mamba/envs/dev/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/user/mamba/envs/dev/lib/python3.10/site-packages/prefect_dask/task_runners.py", line 271, in wait
    return await future.result(timeout=timeout)
TypeError: object State can't be used in 'await' expression
```

# Versions

`prefect-dask` version 0.2.3, with the `prefect version` as the following,

```
Version:             2.10.5
API version:         0.8.4
Python version:      3.10.8
Git commit:          d48dfbbc
Built:               Thu, Apr 20, 2023 4:06 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-dask/#contributing) a pull request to resolve this!

**Comment by madkinsz** [comment] 2023-04-26 02:54
Hey @njthompson-viv this looks like a duplicate of #91 which is fixed in `prefect` main and will be available in the next release.

**Comment by madkinsz** [comment] 2023-04-26 02:54
Thanks for the well written report though!

**Closed by madkinsz** 2023-04-26 02:54 UTC

**Comment by njthompson-viv** [comment] 2023-04-26 02:55
Thanks @madkinsz, great to hear!!
